# Generated by Django 3.1.4 on 2021-03-17 12:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EnergyLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current', models.FloatField(default=0.0)),
                ('set_voltage', models.FloatField(default=230.0)),
                ('energy', models.FloatField(default=0.0)),
                ('date', models.DateField(default=datetime.datetime.now)),
                ('ts', models.IntegerField(verbose_name=1615984908)),
            ],
        ),
    ]
