# Generated by Django 3.1.4 on 2021-03-17 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='energylog',
            name='ts',
            field=models.IntegerField(verbose_name=1615984938),
        ),
    ]
