# Generated by Django 3.1.4 on 2021-03-17 12:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20210317_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='energylog',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='energylog',
            name='ts',
            field=models.IntegerField(verbose_name=1615985204),
        ),
    ]
