# Generated by Django 3.1.4 on 2021-03-17 12:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20210317_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='energylog',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='energylog',
            name='ts',
            field=models.IntegerField(verbose_name=1615985672),
        ),
    ]
