# Generated by Django 3.1.4 on 2021-03-17 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_auto_20210317_1254'),
    ]

    operations = [
        migrations.RenameField(
            model_name='energylog',
            old_name='energy',
            new_name='pwr',
        ),
        migrations.AddField(
            model_name='energylog',
            name='tot_enery',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='energylog',
            name='ts',
            field=models.IntegerField(default=0),
        ),
    ]
