# Generated by Django 3.1.4 on 2021-06-30 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_auto_20210317_1415'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnvironmentalDataLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts', models.IntegerField(default=0)),
                ('temp', models.FloatField(default=0.0)),
                ('humidity', models.FloatField(default=0.0)),
                ('motion', models.BooleanField(default=0)),
            ],
        ),
    ]
