# Generated by Django 3.1.4 on 2021-07-08 15:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_environmentaldatalog'),
    ]

    operations = [
        migrations.CreateModel(
            name='RaspberryPiIp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('ip', models.CharField(max_length=200)),
            ],
        ),
    ]
